apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: kirankalsi/mysql
          ports:
          - name: mysql-port
            containerPort: 3306
          env:
          - name: MYSQL_DATABASE
            value: "core_project"
          - name: MYSQL_ROOT_PASSWORD
            value: "1234"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: kirankalsi/app1
          ports:
          - name: app1-port
            containerPort: 5000
          env:
          - name: DATABASE_URI
            value: "mysql+pymysql://root:1234@mysql:3306/core_project"
          - name: SECRET_KEY
            value: "1234"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: kirankalsi/app2
          ports:
          - name: app2-port
            containerPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: kirankalsi/app3
          ports:
          - name: app3-port
            containerPort: 5002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
  labels:
    app: app4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
        - name: app4
          image: kirankalsi/app4
          ports:
          - name: app4-port
            containerPort: 5003

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app1

---

apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: app4
spec:
  selector:
    app: app4
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP