apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    - containerPort: 80
    env:
    - name: MYSQL_DATABASE
      value: "test_db"
    - name: MYSQL_ROOT_PASSWORD
      value: "root"